on:
  push:
    branches:
      ndak_ada
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ndak_ada
          username: ndak_ada
          password: ndak_ada
          protocol: ftp
          port: 21
          timeout: 60000
