on:
  push:
    branches:
      native_php
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: istesa.net
          username: sumberroda@istesa.net
          password: fKaoF1CRZ1ZG
          protocol: ftp
          port: 21
          timeout: 60000
