on:
  push:
    branches:
      main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: istesa.net
          username: sumberroda
          password: sumberroda@istesa.net
          protocol: ftp
          port: 22
          timeout: 60000
