on:
  push:
    branches:
<<<<<<< HEAD
      - php_mvc
=======
      - master
>>>>>>> 7c5ee7f8ddb6b94f18b7970e907e94404e416e61
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: files.000webhost.com
          username: sumberroda
          password: 4MuE4m&1go2&e4(16^vY
          protocol: ftp
          port: 21
<<<<<<< HEAD
          timeout: 60000
=======
>>>>>>> 7c5ee7f8ddb6b94f18b7970e907e94404e416e61
